// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Creative

import "strconv"

type Clarity int8

const (
	ClarityLD Clarity = 0
	ClaritySD Clarity = 1
	ClarityHD Clarity = 2
)

var EnumNamesClarity = map[Clarity]string{
	ClarityLD: "LD",
	ClaritySD: "SD",
	ClarityHD: "HD",
}

var EnumValuesClarity = map[string]Clarity{
	"LD": ClarityLD,
	"SD": ClaritySD,
	"HD": ClarityHD,
}

func (v Clarity) String() string {
	if s, ok := EnumNamesClarity[v]; ok {
		return s
	}
	return "Clarity(" + strconv.FormatInt(int64(v), 10) + ")"
}
