// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Creative

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CreativeRule struct {
	_tab flatbuffers.Table
}

func GetRootAsCreativeRule(buf []byte, offset flatbuffers.UOffsetT) *CreativeRule {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CreativeRule{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsCreativeRule(buf []byte, offset flatbuffers.UOffsetT) *CreativeRule {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CreativeRule{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *CreativeRule) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CreativeRule) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CreativeRule) Adtype() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CreativeRuleStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CreativeRuleAddAdtype(builder *flatbuffers.Builder, adtype flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(adtype), 0)
}
func CreativeRuleEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
