// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Campaign_

import "strconv"

type costtypeenum int32

const (
	costtypeenumunknown costtypeenum = 0
	costtypeenumcpi     costtypeenum = 1
	costtypeenumcpc     costtypeenum = 2
	costtypeenumcpm     costtypeenum = 3
	costtypeenumcpa     costtypeenum = 4
	costtypeenumcpe     costtypeenum = 5
)

var EnumNamescosttypeenum = map[costtypeenum]string{
	costtypeenumunknown: "unknown",
	costtypeenumcpi:     "cpi",
	costtypeenumcpc:     "cpc",
	costtypeenumcpm:     "cpm",
	costtypeenumcpa:     "cpa",
	costtypeenumcpe:     "cpe",
}

var EnumValuescosttypeenum = map[string]costtypeenum{
	"unknown": costtypeenumunknown,
	"cpi":     costtypeenumcpi,
	"cpc":     costtypeenumcpc,
	"cpm":     costtypeenumcpm,
	"cpa":     costtypeenumcpa,
	"cpe":     costtypeenumcpe,
}

func (v costtypeenum) String() string {
	if s, ok := EnumNamescosttypeenum[v]; ok {
		return s
	}
	return "costtypeenum(" + strconv.FormatInt(int64(v), 10) + ")"
}
