// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stdrank

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type bigtemplate struct {
	_tab flatbuffers.Table
}

func GetRootAsbigtemplate(buf []byte, offset flatbuffers.UOffsetT) *bigtemplate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &bigtemplate{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsbigtemplate(buf []byte, offset flatbuffers.UOffsetT) *bigtemplate {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &bigtemplate{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *bigtemplate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *bigtemplate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *bigtemplate) BigTemplateId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *bigtemplate) MutateBigTemplateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *bigtemplate) SlotList(obj *slotreference, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *bigtemplate) SlotListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func bigtemplateStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func bigtemplateAddBigTemplateId(builder *flatbuffers.Builder, bigTemplateId int32) {
	builder.PrependInt32Slot(0, bigTemplateId, 0)
}
func bigtemplateAddSlotList(builder *flatbuffers.Builder, slotList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(slotList), 0)
}
func bigtemplateStartSlotListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func bigtemplateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
