// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stdrank

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type dcopart struct {
	_tab flatbuffers.Table
}

func GetRootAsdcopart(buf []byte, offset flatbuffers.UOffsetT) *dcopart {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &dcopart{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsdcopart(buf []byte, offset flatbuffers.UOffsetT) *dcopart {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &dcopart{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *dcopart) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *dcopart) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *dcopart) PartId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *dcopart) MutatePartId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *dcopart) ResIdList(j int) int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *dcopart) ResIdListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *dcopart) MutateResIdList(j int, n int64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func dcopartStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func dcopartAddPartId(builder *flatbuffers.Builder, partId int64) {
	builder.PrependInt64Slot(0, partId, 0)
}
func dcopartAddResIdList(builder *flatbuffers.Builder, resIdList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(resIdList), 0)
}
func dcopartStartResIdListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func dcopartEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
