// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stdrank

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type groupcreative struct {
	_tab flatbuffers.Table
}

func GetRootAsgroupcreative(buf []byte, offset flatbuffers.UOffsetT) *groupcreative {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &groupcreative{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsgroupcreative(buf []byte, offset flatbuffers.UOffsetT) *groupcreative {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &groupcreative{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *groupcreative) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *groupcreative) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *groupcreative) GroupId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *groupcreative) CreativeIdList(obj *elementcreative, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *groupcreative) CreativeIdListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func groupcreativeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func groupcreativeAddGroupId(builder *flatbuffers.Builder, groupId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(groupId), 0)
}
func groupcreativeAddCreativeIdList(builder *flatbuffers.Builder, creativeIdList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(creativeIdList), 0)
}
func groupcreativeStartCreativeIdListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func groupcreativeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
