// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stdrank

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type polarisresponse struct {
	_tab flatbuffers.Table
}

func GetRootAspolarisresponse(buf []byte, offset flatbuffers.UOffsetT) *polarisresponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &polarisresponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAspolarisresponse(buf []byte, offset flatbuffers.UOffsetT) *polarisresponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &polarisresponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *polarisresponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *polarisresponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *polarisresponse) Status() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *polarisresponse) MutateStatus(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *polarisresponse) Time() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *polarisresponse) MutateTime(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *polarisresponse) BigTemplateList(obj *bigtemplate, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *polarisresponse) BigTemplateListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *polarisresponse) SlotList(obj *slotobj, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *polarisresponse) SlotListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func polarisresponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func polarisresponseAddStatus(builder *flatbuffers.Builder, status int32) {
	builder.PrependInt32Slot(0, status, 0)
}
func polarisresponseAddTime(builder *flatbuffers.Builder, time int32) {
	builder.PrependInt32Slot(1, time, 0)
}
func polarisresponseAddBigTemplateList(builder *flatbuffers.Builder, bigTemplateList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(bigTemplateList), 0)
}
func polarisresponseStartBigTemplateListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func polarisresponseAddSlotList(builder *flatbuffers.Builder, slotList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(slotList), 0)
}
func polarisresponseStartSlotListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func polarisresponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
