// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stdrank

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type rsresponse struct {
	_tab flatbuffers.Table
}

func GetRootAsrsresponse(buf []byte, offset flatbuffers.UOffsetT) *rsresponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &rsresponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsrsresponse(buf []byte, offset flatbuffers.UOffsetT) *rsresponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &rsresponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *rsresponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *rsresponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *rsresponse) Status() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *rsresponse) MutateStatus(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *rsresponse) Msg() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *rsresponse) Bigtemplateid() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *rsresponse) MutateBigtemplateid(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *rsresponse) Bidresult(obj *campaigninfo, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *rsresponse) BidresultLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *rsresponse) Algorithm() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *rsresponse) Extalgo() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *rsresponse) Predictedecpm() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *rsresponse) MutatePredictedecpm(n float32) bool {
	return rcv._tab.MutateFloat32Slot(16, n)
}

func rsresponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func rsresponseAddStatus(builder *flatbuffers.Builder, status int32) {
	builder.PrependInt32Slot(0, status, 0)
}
func rsresponseAddMsg(builder *flatbuffers.Builder, msg flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(msg), 0)
}
func rsresponseAddBigtemplateid(builder *flatbuffers.Builder, bigtemplateid int64) {
	builder.PrependInt64Slot(2, bigtemplateid, 0)
}
func rsresponseAddBidresult(builder *flatbuffers.Builder, bidresult flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(bidresult), 0)
}
func rsresponseStartBidresultVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func rsresponseAddAlgorithm(builder *flatbuffers.Builder, algorithm flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(algorithm), 0)
}
func rsresponseAddExtalgo(builder *flatbuffers.Builder, extalgo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(extalgo), 0)
}
func rsresponseAddPredictedecpm(builder *flatbuffers.Builder, predictedecpm float32) {
	builder.PrependFloat32Slot(6, predictedecpm, 0.0)
}
func rsresponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
