// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stdrank

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type slotobj struct {
	_tab flatbuffers.Table
}

func GetRootAsslotobj(buf []byte, offset flatbuffers.UOffsetT) *slotobj {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &slotobj{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsslotobj(buf []byte, offset flatbuffers.UOffsetT) *slotobj {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &slotobj{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *slotobj) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *slotobj) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *slotobj) SlotId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *slotobj) MutateSlotId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *slotobj) CampaignTemplateList(obj *campaigntemplate, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *slotobj) CampaignTemplateListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func slotobjStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func slotobjAddSlotId(builder *flatbuffers.Builder, slotId int32) {
	builder.PrependInt32Slot(0, slotId, 0)
}
func slotobjAddCampaignTemplateList(builder *flatbuffers.Builder, campaignTemplateList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(campaignTemplateList), 0)
}
func slotobjStartCampaignTemplateListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func slotobjEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
