// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package stdrank

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type templateelement struct {
	_tab flatbuffers.Table
}

func GetRootAstemplateelement(buf []byte, offset flatbuffers.UOffsetT) *templateelement {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &templateelement{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAstemplateelement(buf []byte, offset flatbuffers.UOffsetT) *templateelement {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &templateelement{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *templateelement) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *templateelement) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *templateelement) ElementName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *templateelement) CreativeIdList(obj *elementcreative, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *templateelement) CreativeIdListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func templateelementStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func templateelementAddElementName(builder *flatbuffers.Builder, elementName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(elementName), 0)
}
func templateelementAddCreativeIdList(builder *flatbuffers.Builder, creativeIdList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(creativeIdList), 0)
}
func templateelementStartCreativeIdListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func templateelementEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
