// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package MyGame

import "strconv"

type Any byte

const (
	AnyNONE    Any = 0
	AnyMonster Any = 1
)

var EnumNamesAny = map[Any]string{
	AnyNONE:    "NONE",
	AnyMonster: "Monster",
}

var EnumValuesAny = map[string]Any{
	"NONE":    AnyNONE,
	"Monster": AnyMonster,
}

func (v Any) String() string {
	if s, ok := EnumNamesAny[v]; ok {
		return s
	}
	return "Any(" + strconv.FormatInt(int64(v), 10) + ")"
}
