// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package std_rank

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BigTemplate struct {
	_tab flatbuffers.Table
}

func GetRootAsBigTemplate(buf []byte, offset flatbuffers.UOffsetT) *BigTemplate {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BigTemplate{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsBigTemplate(buf []byte, offset flatbuffers.UOffsetT) *BigTemplate {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BigTemplate{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *BigTemplate) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BigTemplate) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BigTemplate) Bigtemplateid() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BigTemplate) MutateBigtemplateid(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *BigTemplate) Slotlist(obj *SlotReference, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BigTemplate) SlotlistLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func BigTemplateStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BigTemplateAddBigtemplateid(builder *flatbuffers.Builder, bigtemplateid int64) {
	builder.PrependInt64Slot(0, bigtemplateid, 0)
}
func BigTemplateAddSlotlist(builder *flatbuffers.Builder, slotlist flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(slotlist), 0)
}
func BigTemplateStartSlotlistVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BigTemplateEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
