// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package std_rank

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GroupCreative struct {
	_tab flatbuffers.Table
}

func GetRootAsGroupCreative(buf []byte, offset flatbuffers.UOffsetT) *GroupCreative {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GroupCreative{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsGroupCreative(buf []byte, offset flatbuffers.UOffsetT) *GroupCreative {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GroupCreative{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *GroupCreative) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GroupCreative) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GroupCreative) Groupid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GroupCreative) Creativelist(obj *CreativeIndex, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *GroupCreative) CreativelistLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func GroupCreativeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GroupCreativeAddGroupid(builder *flatbuffers.Builder, groupid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(groupid), 0)
}
func GroupCreativeAddCreativelist(builder *flatbuffers.Builder, creativelist flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(creativelist), 0)
}
func GroupCreativeStartCreativelistVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GroupCreativeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
