// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package std_rank

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Slotobj struct {
	_tab flatbuffers.Table
}

func GetRootAsSlotobj(buf []byte, offset flatbuffers.UOffsetT) *Slotobj {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Slotobj{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSlotobj(buf []byte, offset flatbuffers.UOffsetT) *Slotobj {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Slotobj{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Slotobj) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Slotobj) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Slotobj) Campaigntemplates(obj *CampaignTemplate, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Slotobj) CampaigntemplatesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Slotobj) Slotid() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Slotobj) MutateSlotid(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func SlotobjStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SlotobjAddCampaigntemplates(builder *flatbuffers.Builder, campaigntemplates flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(campaigntemplates), 0)
}
func SlotobjStartCampaigntemplatesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SlotobjAddSlotid(builder *flatbuffers.Builder, slotid int32) {
	builder.PrependInt32Slot(1, slotid, 0)
}
func SlotobjEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
