// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package std_rank

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SlotReference struct {
	_tab flatbuffers.Table
}

func GetRootAsSlotReference(buf []byte, offset flatbuffers.UOffsetT) *SlotReference {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SlotReference{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSlotReference(buf []byte, offset flatbuffers.UOffsetT) *SlotReference {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SlotReference{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SlotReference) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SlotReference) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SlotReference) SlotIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SlotReference) MutateSlotIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *SlotReference) SlotId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SlotReference) MutateSlotId(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func SlotReferenceStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SlotReferenceAddSlotIndex(builder *flatbuffers.Builder, slotIndex int32) {
	builder.PrependInt32Slot(0, slotIndex, 0)
}
func SlotReferenceAddSlotId(builder *flatbuffers.Builder, slotId int32) {
	builder.PrependInt32Slot(1, slotId, 0)
}
func SlotReferenceEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
