// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package std_rank

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TemplateResult struct {
	_tab flatbuffers.Table
}

func GetRootAsTemplateResult(buf []byte, offset flatbuffers.UOffsetT) *TemplateResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TemplateResult{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTemplateResult(buf []byte, offset flatbuffers.UOffsetT) *TemplateResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TemplateResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TemplateResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TemplateResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TemplateResult) Templateid() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TemplateResult) MutateTemplateid(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *TemplateResult) Groupid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TemplateResult) Elementlistresult(obj *TemplateElementResult, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TemplateResult) ElementlistresultLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TemplateResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func TemplateResultAddTemplateid(builder *flatbuffers.Builder, templateid int32) {
	builder.PrependInt32Slot(0, templateid, 0)
}
func TemplateResultAddGroupid(builder *flatbuffers.Builder, groupid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(groupid), 0)
}
func TemplateResultAddElementlistresult(builder *flatbuffers.Builder, elementlistresult flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(elementlistresult), 0)
}
func TemplateResultStartElementlistresultVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TemplateResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
