// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package std_rank

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TemplateElement struct {
	_tab flatbuffers.Table
}

func GetRootAsTemplateElement(buf []byte, offset flatbuffers.UOffsetT) *TemplateElement {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TemplateElement{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTemplateElement(buf []byte, offset flatbuffers.UOffsetT) *TemplateElement {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TemplateElement{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TemplateElement) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TemplateElement) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TemplateElement) Elementname() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TemplateElement) Creativelist(obj *CreativeIndex, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TemplateElement) CreativelistLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func TemplateElementStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func TemplateElementAddElementname(builder *flatbuffers.Builder, elementname flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(elementname), 0)
}
func TemplateElementAddCreativelist(builder *flatbuffers.Builder, creativelist flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(creativelist), 0)
}
func TemplateElementStartCreativelistVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TemplateElementEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
